### ISSUE TITLE
3.0.2 + error: 'MainActor' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by parmar-mehul** [hackiftekhar/IQPullToRefresh#2]
### Bug Report
iOS Deployment min target: iOS 13.0
Xcode 16.1 (16B40)
MacOS 15.1 (24B83)
SPM only -> https://github.com/hackiftekhar/IQPullToRefresh.git -> 3.0.2

#### Current behavior

Getting error as below when build
```
../SourcePackages/checkouts/IQPullToRefresh/IQPullToRefresh/MainActor+AssumeIsolated.swift:25:11: error: 'MainActor' is only available in iOS 13.0 or newer
extension MainActor {

```
![Screenshot 2024-11-07 at 2 33 18 PM](https://github.com/user-attachments/assets/e4055887-00bc-4fca-8a2a-3ae6dcf11823)

#### Expected behavior
Should not get error when compile or build

**Comment by parmar-mehul** [comment]
FYI, "master" branch works fine but v3.0.2 is having issue while using in Xcode 16.1 when compile
Kindly fix this.

Include this two commit & create new version with latest code as 3.0.3
- https://github.com/hackiftekhar/IQPullToRefresh/commit/b5cbad0ec952df44c1402520c93c1cf942c437ae
- https://github.com/hackiftekhar/IQPullToRefresh/commit/519373875e884863218c881cc8d94609a93182da

**Comment by hackiftekhar** [comment]
Done! Thanks for reporting @parmar-mehul
